name: edsb
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - imbalanced-learn
  - xgboost
  - lightgbm
  - expat
  - pyzmq
  - nest-asyncio
  - decorator
  - ucrt
  - wcwidth
  - python-dateutil
  - jedi
  - libsodium
  - wheel
  - comm
  - sqlite
  - vs2015_runtime
  - bzip2
  - libffi
  - xz
  - prompt-toolkit
  - setuptools
  - pip
  - libzlib
  - pure_eval
  - jupyter_core
  - zlib
  - asttokens
  - openssl
  - backcall
  - psutil
  - pygments
  - vc14_runtime
  - pywin32
  - typing-extensions
  - zipp
  - tornado
  - importlib_metadata
  - importlib-metadata
  - packaging
  - exceptiongroup
  - debugpy
  - parso
  - stack_data
  - ipython
  - colorama
  - tzdata
  - tk
  - traitlets
  - matplotlib-inline
  - vc
  - pickleshare
  - executing
  - zeromq
  - typing_extensions
  - ca-certificates
  - jupyter_client
  - platformdirs
  - six
  - ipykernel
  - shap
prefix: C:\Users\SSalvado\Anaconda3\envs\edsb
